{{- if not .Values.paused }}
{{- $fullname := include "app-chart.fullname" . }}
{{- range .Values.externalSecrets }}
{{- $name := printf "%s-%s" $fullname .name }}
---
apiVersion: {{ $.Values.externalSecretsApiVersion }}
kind: ExternalSecret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app-chart.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default "1m" | quote }}
  secretStoreRef:
    name: {{ .store }}
    kind: {{ .storeKind | default "ClusterSecretStore" }}
  target:
    name: {{ $name }}
    creationPolicy: Owner
    template:
      metadata:
        labels:
          {{- include "app-chart.labels" $ | nindent 10 }}
  {{- if .data }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if .dataFrom }}
  dataFrom:
    {{- range .dataFrom }}
    - extract:
        key: {{ .key }}
        {{- if .version }}
        version: {{ .version | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
