{{- if not .Values.paused }}
{{- $fullname := include "app-chart.fullname" . }}
{{- range .Values.secrets }}
{{- if not .secretRef }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app-chart.labels" $ | nindent 4 }}
type: Opaque
{{- if .data }}
data:
  {{- range $k, $v := .data }}
  {{ $k }}: {{ $v | toString | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
